#!/bin/sh

rm config.cache config.status -f

CC=m68k-elf-gcc \
CFLAGS="-m68000 -Os -D__uClinux__ -I/HHDREZ328-R2/uClinux-dist/lib/uClibc/include -I/HHDREZ328-R2/uClinux-dist/linux-2.4.x/include -I/HHDREZ328-R2/uClinux-dist/minigui/m68k-elf/include/ -msep-data " \
LDFLAGS="-Wl,-elf2flt -L/HHDREZ328-R2/uClinux-dist/lib/uClibc/lib -L/HHDREZ328-R2/uClinux-dist/minigui/m68k-elf/lib -lc " \
./configure --prefix=/HHDREZ328-R2/uClinux-dist/minigui/m68k-elf/ \
    --build=i386-linux \
    --host=m68k-elf-linux \
    --target=m68k-elf-linux 

