#!/bin/sh

rm config.cache config.status -f

CC=m68k-elf-gcc \
CFLAGS="-O2 -g -fno-strict-aliasing -fomit-frame-pointer -I/HHCF5249-R3/uClinux-dist/uClibc/include -I/HHCF5249-R3/uClinux-dist/linux-2.4.x/include -I/HHCF5249-R3/uClinux-dist/minigui/m68k-elf/include/ -msep-data -m5200" \
LDFLAGS="-Wl,-elf2flt -Wl,-move-rodata -L/HHCF5249-R3/uClinux-dist/uClibc/lib -L/HHCF5249-R3/uClinux-dist/minigui/m68k-elf/lib -lc" \
./configure \
    --build=i386-linux \
    --host=m68k-elf-linux \
    --target=m68k-elf-linux 

